/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitest;

/**
 *
 * @author Tim Karadeniz
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/bknop.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(0, 420, 423, 78);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/stonks.png"))); // NOI18N
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(470, 0, 680, 360);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Welkom bij Stonks Benc");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(671, 427, 262, 29);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setText("Bied uw pas aan");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(710, 480, 179, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/cKnop.png"))); // NOI18N
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(0, 900, 426, 78);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/dKnop.png"))); // NOI18N
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(1176, 0, 419, 79);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/#Knop.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(1170, 400, 421, 82);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/SKnop.png"))); // NOI18N
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(1175, 904, 420, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/aKnop.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 10, 422, 74);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/enter.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(1170, 400, 420, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/snelp.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(0, 0, 420, 81);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/saldoc.png"))); // NOI18N
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(0, 420, 420, 80);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/zelfbedrag.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(0, 900, 421, 80);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/taal.png"))); // NOI18N
        jLayeredPane1.add(jLabel15);
        jLabel15.setBounds(1170, 400, 420, 80);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/terug naar hoofd.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel16);
        jLabel16.setBounds(0, 0, 421, 80);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setText("U heeft te weinig saldo");
        jLayeredPane1.add(jLabel17);
        jLabel17.setBounds(680, 440, 250, 50);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Bedankt voor uw transactie bij Stonks Benc");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(550, 440, 470, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/5.png"))); // NOI18N
        jLayeredPane1.add(jLabel19);
        jLabel19.setBounds(0, 0, 420, 75);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/10.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel20);
        jLabel20.setBounds(0, 420, 420, 80);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/20.png"))); // NOI18N
        jLayeredPane1.add(jLabel21);
        jLabel21.setBounds(0, 890, 420, 80);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/50.png"))); // NOI18N
        jLabel22.setToolTipText("");
        jLayeredPane1.add(jLabel22);
        jLabel22.setBounds(1180, 0, 410, 80);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/enter.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel23);
        jLabel23.setBounds(1170, 400, 420, 80);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel24.setText("U heeft nog ...... over");
        jLayeredPane1.add(jLabel24);
        jLabel24.setBounds(750, 450, 227, 29);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guitest/images/#Knop.png"))); // NOI18N
        jLayeredPane1.add(jLabel25);
        jLabel25.setBounds(1170, 400, 420, 80);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setText("Voer uw bedrag in");
        jLayeredPane1.add(jLabel18);
        jLabel18.setBounds(700, 450, 200, 30);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 1590, 990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       begin();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        pin();
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
        jLabel5.setEnabled(false);
    jLabel5.setVisible(false);
    jLabel11.setEnabled(true);
    jLabel11.setVisible(true);
    
    
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jLabel5.setEnabled(false);
    jLabel5.setVisible(false);
    jLabel11.setEnabled(true);
    jLabel11.setVisible(true);
    jLabel8.setEnabled(false);
    jLabel8.setVisible(false);
    jLabel9.setEnabled(false);
    jLabel9.setVisible(false);
   
    
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
        snelP();
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        terugNaarHoofd();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
          jLabel16.setEnabled(true);
    jLabel16.setVisible(true);
    jLabel12.setEnabled(false);
    jLabel12.setVisible(false);
    jLabel2.setEnabled(true);
    jLabel2.setVisible(true);
    jLabel13.setEnabled(false);
    jLabel13.setVisible(false);
    jLabel14.setEnabled(false);
    jLabel14.setVisible(false);
    jLabel3.setEnabled(true);
    jLabel3.setVisible(true);
    jLabel15.setEnabled(false);
    jLabel15.setVisible(false);
    jLabel18.setEnabled(true);
    jLabel18.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        jLabel16.setEnabled(false);
    jLabel16.setVisible(false);
    jLabel19.setEnabled(true);
    jLabel19.setVisible(true);
    jLabel2.setEnabled(false);
    jLabel2.setVisible(false);
    jLabel20.setEnabled(true);
    jLabel20.setVisible(true);
    jLabel3.setEnabled(false);
    jLabel3.setVisible(false);
    jLabel21.setEnabled(true);
    jLabel21.setVisible(true);
    jLabel4.setEnabled(false);
    jLabel4.setVisible(false);
    jLabel22.setEnabled(true);
    jLabel22.setVisible(true);
    jLabel23.setEnabled(false);
    jLabel23.setVisible(false);
    jLabel5.setEnabled(true);
    jLabel5.setVisible(true);
    jLabel18.setEnabled(false);
    jLabel18.setVisible(false);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        jLabel20.setEnabled(false);
    jLabel20.setVisible(false);
jLabel21.setEnabled(false);
    jLabel21.setVisible(false);
    jLabel22.setEnabled(false);
    jLabel22.setVisible(false);
    jLabel23.setEnabled(false);
    jLabel23.setVisible(false);
    jLabel4.setEnabled(true);
    jLabel4.setVisible(true);
    snelP();
    }//GEN-LAST:event_jLabel20MouseClicked
void begin (){
    jLabel10.setEnabled(false);
    jLabel10.setVisible(false);
    jLabel11.setEnabled(false);
    jLabel11.setVisible(false);
    jLabel12.setEnabled(false);
    jLabel12.setVisible(false);
    jLabel13.setEnabled(false);
    jLabel13.setVisible(false);
    jLabel14.setEnabled(false);
    jLabel14.setVisible(false);
    jLabel15.setEnabled(false);
    jLabel15.setVisible(false);
    jLabel15.setEnabled(false);
    jLabel15.setVisible(false);
    jLabel16.setEnabled(false);
    jLabel16.setVisible(false);
    jLabel17.setEnabled(false);
    jLabel17.setVisible(false);
    jLabel18.setEnabled(false);
    jLabel18.setVisible(false);
    jLabel24.setEnabled(false);
    jLabel24.setVisible(false);
    jLabel25.setEnabled(true);
    jLabel25.setVisible(true);
    
}
void pin (){
    jLabel1.setEnabled(false);
    jLabel1.setVisible(false);
    jLabel2.setEnabled(false);
    jLabel2.setVisible(false);
    jLabel3.setEnabled(false);
    jLabel3.setVisible(false);
    jLabel5.setEnabled(false);
    jLabel5.setVisible(false);
    jLabel12.setEnabled(true);
    jLabel12.setVisible(true);
    jLabel13.setEnabled(true);
    jLabel13.setVisible(true);
    jLabel14.setEnabled(true);
    jLabel14.setVisible(true);
    jLabel15.setEnabled(true);
    jLabel15.setVisible(true);
    jLabel11.setEnabled(false);
    jLabel11.setVisible(false);
   jLabel8.setEnabled(false);
    jLabel8.setVisible(false);
    jLabel9.setEnabled(false);
    jLabel9.setVisible(false);
   
}    
void  snelP(){
    jLabel16.setEnabled(true);
    jLabel16.setVisible(true);
    jLabel12.setEnabled(false);
    jLabel12.setVisible(false);
    jLabel2.setEnabled(true);
    jLabel2.setVisible(true);
    jLabel13.setEnabled(false);
    jLabel13.setVisible(false);
    jLabel14.setEnabled(false);
    jLabel14.setVisible(false);
    jLabel3.setEnabled(true);
    jLabel3.setVisible(true);
    jLabel10.setEnabled(true);
    jLabel10.setVisible(true);
    
}
void terugNaarHoofd(){
  jLabel16.setEnabled(false);
    jLabel16.setVisible(false);
    jLabel12.setEnabled(true);
    jLabel12.setVisible(true);
    jLabel2.setEnabled(false);
    jLabel2.setVisible(false);
    jLabel13.setEnabled(true);
    jLabel13.setVisible(true);
    jLabel14.setEnabled(true);
    jLabel14.setVisible(true);
    jLabel3.setEnabled(false);
    jLabel3.setVisible(false);
     jLabel24.setEnabled(false);
    jLabel24.setVisible(false);
}
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
